# Generated by Django 2.2 on 2020-08-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_property_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
