# Generated by Django 2.2 on 2020-09-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_featuredproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name='featuredproperty',
            options={'verbose_name_plural': 'Featured Properties'},
        ),
        migrations.AddField(
            model_name='featuredproperty',
            name='link',
            field=models.CharField(default='homeplanify.com', max_length=256),
            preserve_default=False,
        ),
    ]
