# Generated by Django 2.2 on 2021-03-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadgrow', '0003_label_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='customer',
        ),
        migrations.AddField(
            model_name='label',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labelled', to='leadgrow.Business'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='event_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='labels',
            field=models.ManyToManyField(null=True, related_name='customer_labels', to='leadgrow.Label'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='property_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
