# Generated by Django 2.2 on 2021-03-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgrow', '0004_auto_20210319_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
