# Generated by Django 2.2 on 2021-04-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadgrow', '0006_auto_20210325_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labelled', to='leadgrow.Business'),
        ),
    ]
