# Generated by Django 2.2 on 2021-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feawa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='agent_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firm',
            name='logo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
