# Generated by Django 2.2 on 2021-03-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feawa', '0002_auto_20210319_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feawa.Zone'),
        ),
    ]
